# Generated by Django 3.1.4 on 2020-12-05 18:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='matrícula')),
                ('cuit', models.CharField(blank=True, max_length=14, verbose_name='CUIT')),
            ],
            options={
                'verbose_name_plural': 'profesionales',
                'ordering': ['matricula'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Actuantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveSmallIntegerField(default=10, help_text='Medición, gabinete, gestiones y trámites.')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horas', 'profesional'],
            },
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('combustible', models.CharField(choices=[('n', 'Nafta'), ('p', 'Nafta Premium'), ('d', 'Diesel'), ('l', 'Diesel Premium'), ('g', 'GNC')], default='n', max_length=1)),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['combustible'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('horas_semanales', models.PositiveSmallIntegerField(default=40)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instrumental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornadas', models.PositiveSmallIntegerField(default=1, help_text='Jornadas de utilización.')),
            ],
            options={
                'ordering': ['-jornadas', 'instrumento'],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor_USD', models.DecimalField(decimal_places=2, help_text='Valor de reposición en dólares. Cotización dólar oficial según Banco Nación.', max_digits=8)),
                ('vida_util', models.PositiveIntegerField(default=200, help_text='Vida útil esperada en jornadas de trabajo y/o gabinete.', verbose_name='vida útil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='costos.empresa')),
            ],
            options={
                'ordering': ['nombre', 'valor_USD'],
            },
        ),
        migrations.CreateModel(
            name='Movilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveSmallIntegerField(default=70, help_text='Kilomtraje estimado.')),
            ],
            options={
                'ordering': ['-km', 'vehiculo'],
            },
        ),
        migrations.CreateModel(
            name='ParametroGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cotizacion_dolar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cotización del dólar')),
                ('modulo_tributario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='módulo tributario SCIT')),
            ],
            options={
                'verbose_name': 'parámetro global',
                'verbose_name_plural': 'parámetros globales',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de gasto',
                'verbose_name_plural': 'tipos de gastos',
                'ordering': ['detalle'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor de reposición actualizado en pesos.', max_digits=10)),
                ('kilometraje_anual', models.PositiveIntegerField(default=20000, help_text='KM estimados para un año.')),
                ('rendimiento', models.PositiveSmallIntegerField(default=9, help_text='Rendimiento promedio en km por litro.', verbose_name='rendimiento [km/l]')),
                ('costo_patente', models.DecimalField(decimal_places=2, default=0, help_text='Costo de cada cuota de la patente.', max_digits=8)),
                ('costo_seguro', models.DecimalField(decimal_places=2, default=0, help_text='Costo mensual del seguro.', max_digits=8)),
                ('costo_cochera', models.DecimalField(decimal_places=2, default=0, help_text='Costo mensual de cochera / garage.', max_digits=8)),
                ('costo_lubricante', models.DecimalField(decimal_places=2, default=0, help_text='Costo del lubricante (calcula cada 6 meses).', max_digits=8)),
                ('costo_lavado', models.DecimalField(decimal_places=2, default=0, help_text='Gastos mensuales en lavado.', max_digits=8)),
                ('costo_neumatico', models.DecimalField(decimal_places=2, default=0, help_text='Costo de 1 neumático (calcula cada 40.000 km).', max_digits=8)),
                ('costo_service', models.DecimalField(decimal_places=2, default=0, help_text='Costo de Service general (calcula cada 10.000 km).', max_digits=8)),
                ('costo_anual_reparaciones', models.DecimalField(decimal_places=2, default=0, help_text='Estimado de reparaciones por año.', max_digits=8)),
                ('costo_rto', models.DecimalField(decimal_places=2, default=0, help_text='Costo de Revisión Técnica Obligatoria.', max_digits=8, verbose_name='RTO')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='costos.empresa')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.combustible')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['nombre', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de cálculo de costos.')),
                ('expediente', models.PositiveIntegerField(blank=True, help_text='Expediente CoPA relacionado.', null=True)),
                ('comitente', models.CharField(blank=True, max_length=50)),
                ('aporte_copa', models.DecimalField(decimal_places=2, default=2200, help_text='Calculados según Sistema.', max_digits=10, verbose_name='aportes CoPA')),
                ('aporte_caja', models.DecimalField(decimal_places=2, default=2890, help_text='Calculados según Sistema.', max_digits=10, verbose_name='aportes Caja')),
                ('partidas', models.PositiveSmallIntegerField(default=1, help_text='Para cálculo de Sellados Fiscales e Informes Catastrales.')),
                ('lotes_finales', models.PositiveSmallIntegerField(default=1, help_text='Para cálculo de Sellados Fiscales.')),
                ('escrituras', models.DecimalField(decimal_places=2, default=0, help_text='Gastos por pedidos de escrituras al RGP.', max_digits=8)),
                ('visados', models.DecimalField(decimal_places=2, default=0, help_text='Visados en reparticiones públicas.', max_digits=8)),
                ('ccu', models.DecimalField(decimal_places=2, default=0, help_text='Sellados por CCU.', max_digits=8, verbose_name='Certificado Catastral Urgente')),
                ('estudio_titulos', models.DecimalField(decimal_places=2, default=0, help_text='Gastos extra por Estudio de Títulos.', max_digits=8, verbose_name='estudio de títulos')),
                ('georreferenciacion', models.DecimalField(decimal_places=2, default=0, help_text='Gastos extra por Georreferenciación.', max_digits=8, verbose_name='georreferenciación')),
                ('citaciones', models.DecimalField(decimal_places=2, default=0, help_text='Estampillados por notificaciones.', max_digits=8)),
                ('viaticos', models.DecimalField(decimal_places=2, default=0, help_text='Alojamiento y comidas.', max_digits=8, verbose_name='viáticos')),
                ('ayudante', models.DecimalField(decimal_places=2, default=0, help_text='Horas / jornales de ayudante/s.', max_digits=8)),
                ('dibujante', models.DecimalField(decimal_places=2, default=0, help_text='Horas / jornales de dibujante/s.', max_digits=8)),
                ('impresiones', models.DecimalField(decimal_places=2, default=0, help_text='Ploteos o impresiones de documentación.', max_digits=8)),
                ('mojones', models.DecimalField(decimal_places=2, default=0, help_text='Hierros, estacas, pintura, cintas peligro...', max_digits=8)),
                ('gestor', models.DecimalField(decimal_places=2, default=0, help_text='Gestores, comisionistas, fletes.', max_digits=8)),
                ('seguros_especiales', models.DecimalField(decimal_places=2, default=0, help_text='Seguros ocasionales o especiales para este trabajo.', max_digits=8)),
                ('alquiler_instrumentos', models.DecimalField(decimal_places=2, default=0, help_text='Alquileres de instrumentos ocasionales para este trabajo.', max_digits=8)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, help_text='Otros gastos sin categorizar.', max_digits=8)),
                ('instrumentos', models.ManyToManyField(blank=True, through='costos.Instrumental', to='costos.Instrumento')),
                ('profesionales', models.ManyToManyField(through='costos.Actuantes', to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(blank=True, through='costos.Movilidad', to='costos.Vehiculo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='movilidad',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movilidad', to='costos.trabajo'),
        ),
        migrations.AddField(
            model_name='movilidad',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='costos.vehiculo'),
        ),
        migrations.AddField(
            model_name='instrumental',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='costos.instrumento'),
        ),
        migrations.AddField(
            model_name='instrumental',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumental', to='costos.trabajo'),
        ),
        migrations.CreateModel(
            name='GastoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Cuatrimestral'), (180, 'Semestral'), (360, 'Anual')], default=30)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.tipogasto')),
            ],
            options={
                'verbose_name': 'gasto personal',
                'verbose_name_plural': 'gastos personales',
                'ordering': ['tipo', '-monto'],
            },
        ),
        migrations.CreateModel(
            name='GastoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Cuatrimestral'), (180, 'Semestral'), (360, 'Anual')], default=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='costos.empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.tipogasto')),
            ],
            options={
                'verbose_name': 'gasto general',
                'verbose_name_plural': 'gastos generales',
                'ordering': ['tipo', '-monto'],
            },
        ),
        migrations.AddField(
            model_name='actuantes',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuantes', to='costos.trabajo'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='costos.empresa'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
