# Generated by Django 3.1.2 on 2020-11-06 03:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(max_length=7, unique=True, verbose_name='matrícula')),
                ('cuit', models.CharField(blank=True, max_length=14, verbose_name='CUIT')),
            ],
            options={
                'verbose_name_plural': 'profesionales',
                'ordering': ['matricula'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('p', 'Nafta Premium'), ('n', 'Nafta'), ('d', 'Diesel'), ('g', 'GNC')], default='n', max_length=1)),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['combustible', '-fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('horas_semanales', models.PositiveSmallIntegerField(default=40)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de gasto',
                'verbose_name_plural': 'tipos de gastos',
                'ordering': ['detalle'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor_a_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje_anual', models.PositiveIntegerField()),
                ('rendimiento', models.PositiveSmallIntegerField(default=9, verbose_name='rendimiento [km/l]')),
                ('costo_mensual_patente', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_mensual_seguro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_mensual_cochera', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_lubricante', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('costo_lavado', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('costo_neumatico', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('costo_service', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_anual_reparaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='costos.empresa')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.combustible')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['nombre', 'valor_a_nuevo'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('expediente', models.PositiveIntegerField(blank=True)),
                ('comitente', models.CharField(max_length=50)),
                ('aporte_copa', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('aporte_caja', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('partidas', models.PositiveSmallIntegerField(blank=True)),
                ('lotes_finales', models.PositiveSmallIntegerField(blank=True)),
                ('distancia_km', models.PositiveIntegerField(blank=True)),
                ('horas', models.PositiveSmallIntegerField(default=10)),
                ('visado_municipio', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('escrituras', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('ayudante', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('dibujante', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('impresiones', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('ccu', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('mojones', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('comisiones', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('citaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('seguros_especiales', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('alquiler_instrumentos', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('profesionales', models.ManyToManyField(related_name='trabajos', to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(related_name='trabajos', to='costos.Vehiculo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor_USD', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vida_util', models.PositiveIntegerField(default=5, help_text='Vida útil esperada en años.', verbose_name='vida útil')),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece.', on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='costos.empresa')),
            ],
            options={
                'ordering': ['nombre', 'valor_USD'],
            },
        ),
        migrations.CreateModel(
            name='GastoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Cuatrimestral'), (180, 'Semestral'), (365, 'Anual')], default='30')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.tipogasto')),
            ],
            options={
                'verbose_name': 'gasto personal',
                'verbose_name_plural': 'gastos personales',
            },
        ),
        migrations.CreateModel(
            name='GastoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Cuatrimestral'), (180, 'Semestral'), (365, 'Anual')], default='30')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='costos.empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.tipogasto')),
            ],
            options={
                'verbose_name': 'gasto general',
                'verbose_name_plural': 'gastos generales',
            },
        ),
        migrations.AddField(
            model_name='profesional',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='costos.empresa'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
