# Generated by Django 3.1.2 on 2020-11-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0002_auto_20201106_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='comisiones',
            new_name='gestor',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='estudio_titulos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='estudio de títulos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='georreferenciacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='georreferenciación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='instrumentos',
            field=models.ManyToManyField(related_name='trabajos', to='costos.Instrumento'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='combustible',
            field=models.CharField(choices=[('p', 'Nafta Premium'), ('n', 'Nafta'), ('l', 'Diesel Premium'), ('d', 'Diesel'), ('g', 'GNC')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='ccu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='certificado catastral urgente'),
        ),
    ]
