# Generated by Django 3.1.4 on 2020-12-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0002_auto_20201208_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combustible',
        ),
    ]
