# Generated by Django 3.1.4 on 2020-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_delete_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='alquiler_instrumentos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago de alquileres ocasionales para este trabajo.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='aporte_caja',
            field=models.DecimalField(decimal_places=2, default=2890, help_text='Monto calculado según Sistema.', max_digits=10, verbose_name='aportes Caja'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='aporte_copa',
            field=models.DecimalField(decimal_places=2, default=2200, help_text='Monto calculado según Sistema.', max_digits=10, verbose_name='aportes CoPA'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='ayudante',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago de jornales a ayudante/s.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='ccu',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago de sellados por CCU.', max_digits=8, verbose_name='Certificado Catastral Urgente'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='citaciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago de envío / estampillados por notificaciones.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='dibujante',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago a dibujante/s.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='escrituras',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gasto por pedidos al RGP.', max_digits=8, verbose_name='monto por escrituras'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='gestor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago a gestores, comisionistas, fletes.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='impresiones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago por ploteos / impresiones de documentación.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='mojones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gasto en hierros, estacas, pintura, cintas peligro.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='partidas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Para cálculo de Sellados Fiscales e Informes Catastrales.', verbose_name='cantidad de partidas'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='seguros_especiales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago de seguros ocasionales para este trabajo.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='viaticos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pago de alojamiento / comidas.', max_digits=8, verbose_name='viáticos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='visados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gastos en reparticiones públicas.', max_digits=8, verbose_name='monto por visados'),
        ),
    ]
