# Generated by Django 3.1.2 on 2020-11-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_auto_20201107_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='cantidad_de_trabajos',
            field=models.PositiveSmallIntegerField(default=100, help_text='Vida útil esperada en cantidad de trabajos.', verbose_name='# trabajos'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='costos.empresa'),
        ),
    ]
