# Generated by Django 3.1.2 on 2020-11-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0004_auto_20201107_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustible',
            options={'ordering': ['combustible']},
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='fecha_desde',
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='fecha_hasta',
        ),
    ]
