# Generated by Django 3.1.4 on 2020-12-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0004_auto_20201211_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametroGlobal',
        ),
    ]
