# Generated by Django 3.1.2 on 2020-11-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0005_auto_20201108_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='dias',
            field=models.PositiveSmallIntegerField(default=1, help_text='Jornadas de trabajo.', verbose_name='días'),
        ),
    ]
