# Generated by Django 3.1.4 on 2020-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0005_delete_parametroglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movilidad',
            name='km',
            field=models.PositiveSmallIntegerField(default=70, help_text='Kilometraje estimado.'),
        ),
    ]
