# Generated by Django 3.1.2 on 2020-11-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0006_trabajo_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='dias',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='jornadas_de_medicion',
            field=models.PositiveSmallIntegerField(default=1, help_text='Jornadas de utilización de instrumentos.', verbose_name='jornadas de medición'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='horas',
            field=models.PositiveSmallIntegerField(default=10, help_text='Horas de medición y gabinete.'),
        ),
    ]
