# Generated by Django 3.1.2 on 2020-11-21 05:26

import costos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0006_auto_20201121_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoempresa',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(costos.models.Periodo['DIA'], 'Diario'), (costos.models.Periodo['SEMANA'], 'Semanal'), (costos.models.Periodo['MES'], 'Mensual'), (costos.models.Periodo['BIMESTRE'], 'Bimestral'), (costos.models.Periodo['TRIMESTRE'], 'Trimestral'), (costos.models.Periodo['CUATRIMESTRE'], 'Cuatrimestral'), (costos.models.Periodo['SEMESTRE'], 'Semestral'), (costos.models.Periodo['AÑO'], 'Anual')], default=costos.models.Periodo['MES']),
        ),
        migrations.AlterField(
            model_name='gastopersonal',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(costos.models.Periodo['DIA'], 'Diario'), (costos.models.Periodo['SEMANA'], 'Semanal'), (costos.models.Periodo['MES'], 'Mensual'), (costos.models.Periodo['BIMESTRE'], 'Bimestral'), (costos.models.Periodo['TRIMESTRE'], 'Trimestral'), (costos.models.Periodo['CUATRIMESTRE'], 'Cuatrimestral'), (costos.models.Periodo['SEMESTRE'], 'Semestral'), (costos.models.Periodo['AÑO'], 'Anual')], default=costos.models.Periodo['MES']),
        ),
    ]
