# Generated by Django 3.1.4 on 2020-12-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0006_auto_20201224_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='horas_semanales',
            field=models.PositiveSmallIntegerField(default=40, help_text='Horas de trabajo por semana.'),
        ),
    ]
