# Generated by Django 3.1.4 on 2021-05-28 16:29

import costos.preferences
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0007_auto_20201230_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='aporte_caja',
            field=models.DecimalField(decimal_places=2, default=costos.preferences.get_aporte_caja, help_text='Monto calculado según Sistema.', max_digits=10, verbose_name='aportes Caja'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='aporte_copa',
            field=models.DecimalField(decimal_places=2, default=costos.preferences.get_aporte_copa, help_text='Monto calculado según Sistema.', max_digits=10, verbose_name='aportes CoPA'),
        ),
    ]
