# Generated by Django 3.1.2 on 2020-11-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0008_auto_20201109_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='expediente',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
