# Generated by Django 3.1.4 on 2024-10-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0009_auto_20241001_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='jornadas',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Jornadas de utilización. (Admite fracción)', max_digits=4),
        ),
    ]
