# Generated by Django 3.1.2 on 2020-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0009_auto_20201109_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='alquiler_instrumentos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='aporte_caja',
            field=models.DecimalField(decimal_places=2, default=2890, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='aporte_copa',
            field=models.DecimalField(decimal_places=2, default=2200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='ayudante',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='ccu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='certificado catastral urgente'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='citaciones',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='dibujante',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='distancia_km',
            field=models.PositiveIntegerField(blank=True, default=70),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='escrituras',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estudio_titulos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='estudio de títulos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='georreferenciacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='georreferenciación'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='gestor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='horas',
            field=models.PositiveSmallIntegerField(default=10, help_text='Horas de medición, gabinete, gestiones y trámites.'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='impresiones',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='costos.Instrumento'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='lotes_finales',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='mojones',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='partidas',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='seguros_especiales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='vehiculos',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='costos.Vehiculo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='visado_municipio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
